[[datasets]]
resolution = 1024
batch_size = 1

  [[datasets.subsets]]
  image_dir = "/home/tsondo/kohya_ss/dataset/images/talia 40"
  class_tokens = "talia"
  num_repeats = 40
  caption_extension = ".txt"
