# General training parameters
output_dir = "/home/tsondo/kohya_ss/outputs"
output_name = "test_talia"
logging_dir = "/home/tsondo/kohya_ss/logs"

# Model
pretrained_model_name_or_path = "/home/tsondo/kohya_ss/models/realismByStableYogi_v60FP16.safetensors"

# Dataset
dataset_config = "/home/tsondo/kohya_ss/dataset_lora.toml"

# Training
network_module = "networks.lora"
network_dim = 16
network_alpha = 16
network_train_unet_only = true
train_batch_size = 1
learning_rate = 1e-4
max_train_steps = 100
save_every_n_steps = 50
mixed_precision = "bf16"

# Output format
save_model_as = "safetensors"
save_precision = "bf16"
